// Generated by CoffeeScript 1.10.0
(function() {
  var collectInlineStyles, collectWalker;

  collectWalker = (function() {
    var attrs;
    attrs = [];
    return function(root) {
      var attr, i, len, node, ref, ref1;
      if (root.tag == null) {
        return;
      }
      if (((ref = root.attrs) != null ? ref.style : void 0) != null) {
        attr = {
          "class": (function() {
            if (root.attrs["class"]) {
              return '.' + root.attrs["class"].split(/\s/)[0];
            } else {
              return root.tag;
            }
          })(),
          style: root.attrs.style
        };
        attrs.push(attr);
        root.attrs.style = false;
      }
      if (root.content != null) {
        ref1 = root.content;
        for (i = 0, len = ref1.length; i < len; i++) {
          node = ref1[i];
          collectWalker(node);
        }
      }
      return attrs;
    };
  })();

  collectInlineStyles = function(tree) {
    var attrs;
    attrs = null;
    return tree.match({
      tag: 'body'
    }, function(node) {
      attrs = collectWalker(node);
      return node;
    }).match({
      tag: 'head'
    }, function(node) {
      var attr, content, css, dcrls, i, len, tag;
      tag = 'style';
      content = ["\n"];
      for (i = 0, len = attrs.length; i < len; i++) {
        attr = attrs[i];
        dcrls = (function() {
          dcrls = attr.style.split(/;/).filter(function(dcrl) {
            return !/^[\n\s]*$/.test(dcrl);
          }).map(function(dcrl) {
            var replaced;
            replaced = dcrl.replace(/^[\n\s]*|[\n\s]*$/, '');
            return '  ' + replaced + ";\n";
          });
          return dcrls;
        })();
        css = (function() {
          var selector;
          selector = [attr["class"] + " {\n", "}\n"];
          Array.prototype.splice.apply(selector, [1, 0].concat(dcrls));
          return selector;
        })();
        content = content.concat(css);
      }
      node.content.push({
        tag: tag,
        content: content
      });
      node.content.push("\n");
      return node;
    });
  };

  module.exports = collectInlineStyles;

}).call(this);
